# DCP 1.0
apiVersion: fpga.intel.com/v1
kind: FpgaRegion
metadata:
  name: arria10.dcp1.0
spec:
  interfaceId: ce48969398f05f33946d560708be108a
---
# DCP 1.1
apiVersion: fpga.intel.com/v1
kind: FpgaRegion
metadata:
  name: arria10.dcp1.1
spec:
  interfaceId: 9926ab6d6c925a68aabca7d84c545738
---
# DCP 1.2
apiVersion: fpga.intel.com/v1
kind: FpgaRegion
metadata:
  name: arria10.dcp1.2
spec:
  interfaceId: 69528db6eb31577a8c3668f9faa081f6
---
# D5005
apiVersion: fpga.intel.com/v1
kind: FpgaRegion
metadata:
  name: d5005
spec:
  interfaceId: bfac4d851ee856fe8c95865ce1bbaa2d
