language: go

go:
  - 1.10.x

sudo: required

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/fzipp/gocyclo
  # hack for building on forks
  - repo=`basename $PWD`; src=`dirname $PWD`; dest="`dirname $src`/intel"
  - if [[ "$src" != "$dest" ]]; then mv "$src" "$dest"; cd ../../intel/$repo; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$repo; fi
script:
  - make format
  - make lint
  - make
  - make vet
  - make cyclomatic-check
  - make test
  - make images
  - make demos

after_success:
  - bash <(curl -s https://codecov.io/bash)
