# permissions for end users to edit fpgadeviceplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fpgadeviceplugin-editor-role
rules:
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - fpgadeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - fpgadeviceplugins/status
  verbs:
  - get
