# permissions for end users to edit gpudeviceplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpudeviceplugin-editor-role
rules:
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - gpudeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - gpudeviceplugins/status
  verbs:
  - get
