# permissions for end users to edit qatdeviceplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qatdeviceplugin-editor-role
rules:
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - qatdeviceplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deviceplugin.intel.com
  resources:
  - qatdeviceplugins/status
  verbs:
  - get
