apiVersion: extensions/v1beta1
kind: Deployment
metadata:
      name: intel-fpga-webhook-deployment
      labels:
        app: intel-fpga-webhook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: intel-fpga-webhook
    spec:
      containers:
        - name: fpga-mutator
          image: intel/intel-fpga-admissionwebhook:0.15.0-rc.1
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-private-key-file=/etc/webhook/certs/key.pem
            - -mode={MODE}
            - -debug
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: intel-fpga-webhook-certs
