apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fpgaregions.fpga.intel.com
spec:
  group: fpga.intel.com
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
  names:
    plural: fpgaregions
    singular: fpgaregion
    kind: FpgaRegion
    shortNames:
    - fpga
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            interfaceId:
              type: string
              pattern: '^[0-9a-f]{8,32}$'
