apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: acceleratorfunctions.fpga.intel.com
spec:
  group: fpga.intel.com
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
  names:
    plural: acceleratorfunctions
    singular: acceleratorfunction
    kind: AcceleratorFunction
    shortNames:
    - af
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            afuId:
              type: string
              pattern: '^[0-9a-f]{8,32}$'
            interfaceId:
              type: string
              pattern: '^[0-9a-f]{8,32}$'
            mode:
              type: string
              pattern: '^af|region$'
