kind: ServiceAccount
apiVersion: v1
metadata:
  name: sgx-epc-extres
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sgx-epc-extres-rd
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  verbs:
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sgx-epc-extres-rd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sgx-epc-extres-rd
subjects:
- kind: ServiceAccount
  name: sgx-epc-extres
  namespace: kube-system
