bases:
  - ../../base

resources:
  - fpgaregion-crd.yaml
  - fpgaregions.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: intel-fpga-webhook-deployment
    path:
      change-mode-orchestrated.yaml
